--- #YAML:1.0
name:                   Regexp-Log-Common
version:                0.10
abstract:               Enables simple parsing of (Extended) Common Log Format log files.
author:
  - Barbie <barbie@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

requires:
  perl:                   5.006
  Regexp::Log:            0
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  Regexp::Log::Common:
    file:     lib/Regexp/Log/Common.pm
    version:  0.10
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Regexp-Log-Common
  repository: http://github.com/barbie/regexp-log-common

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
