--- #YAML:1.0
name:                   Regexp-Log-Common
version:                0.07
abstract:               Enables simple parsing of (Extended) Common Log Format log files.
author:
  - Barbie <barbie@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

requires:
  perl:                   5.006
  Regexp::Log:            0
recommends:
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
build_requires:
  Test::More:             0.70
  IO::File:               0

provides:
  Regexp::Log::Common:
    file:     lib/Regexp/Log/Common.pm
    version:  0.07
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
