--- #YAML:1.0
name:                   Regexp-Log-Common
version:                0.05
abstract:               Enables simple parsing of (Extended) Common Log Format log files.
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  Regexp::Log:          0
  Test::More:           0.47
recommends:
  Test::More:           0.47
  Test::Pod:            1.00
  Test::Pod::Coverage:  0.08
  Test::YAML::Meta:     0
build_requires:
  Test::More:           0.47

provides:
  Regexp::Log::Common:
    file:     lib/Regexp/Log/Common.pm
    version:  0.05
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.3
   url:       http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
